apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      node.kubernetes.io/compute: ec2
  template:
    metadata:
      labels:
        node.kubernetes.io/compute: ec2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80